### ISSUE TITLE
Spectramax Input

### ISSUE THREAD

**Issue by EGCGDanForth** [EdinburghGenomics/clarity_scripts#13]
Up to 3 plates can be run on the spectramax in one session. The Softmax spectramax software requires each plate template to be loaded into the software individually. The Clarity out of the box sample sheet generator cannot create seperate files for each container. A script is need to create individual plate templates per container in one LIMS step that can be accepted by the Softmax software.

**Comment by tcezard** [comment]
Issue put on hold for now until Seqlab2 is installed

**Comment by tcezard** [comment]
This should now be revived now.

**Comment by mwhamgenomics** [comment]
This was closed in #31.
