### ISSUE TITLE
Parse data to a submitted sample using UDF contents as a reference

### ISSUE THREAD

**Issue by EGCGDanForth** [EdinburghGenomics/clarity_scripts#17]
I want to be able to parse multiple fields to submitted samples using the 2D Barcode UDF as the reference. The input for the parsing will be the Sample Submission Manifest. Ideally, I would like the arguments of the script to allow me to map a variable number of columns in the Sample Submission Manifest to submitted sample UDFs eg.. --mappingUDF 'Prep Workflow:Prep Workflow' --mappingUDF 'Tissue Type:Tissue Type'  where the left side of each argument is the manifest column and the right side is the submitted sample udf.

**Comment by tcezard** [comment]
Do you want this script to create the sample or we assume the sample are already created and just add new UDFs?

**Comment by tcezard** [comment]
It has been done
