### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/clarity_scripts#18]
Before starting work on the Lims automation, we should clean up this repo:
- PEP8 refactor
- [EGCG-Core](http://github.com/EdinburghGenomics/EGCG-Core) logging, etc.
- moar tests

**Comment by mwhamgenomics** [comment]
Are we running these scripts under Python 2? If we are, that could be a problem, as EGCG-Core is Python 3.

**Comment by tcezard** [comment]
I believe this is now done
