### ISSUE TITLE
Script to queue plate to discard

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/clarity_scripts#2]
This script will be called from the LIMS web interface through a trigger providing a process id
it will:
 1. find all the samples going through that step
 2. find all the artifacts (Analytes) associated with those samples
 3. find all the containers associated with those artifacts
 4. finds all the artifacts associated with these containers not associated with samples in 1.
 5. go through each of the containers in 3 and route their artifacts if the root artifacts of all those artifacts have been through "Discard Sample" workflow

We need to avoid making too many queries to the LIMS so as much as possible, gather all the ids then make a search query then fetch the object using batch.

**Comment by tcezard** [comment]
Caron mentioned that some containers do not need to be queued because they either don't exist or have been discarded already. These container will have the following suffixes:
``` 
-QNT
-CFP
-NRM
-IMP
-SSI
-ALP
-CAP
-PCR
-CPP
-LQC
-DQC1
-DIL1
-DIL2
-QPCR
-CST
```
or container of type
```
Patterned Flowcell
```

**Comment by EGCGDanForth** [comment]
I think point 5 should updated to something like:

5. go through each of the containers in 3 and route their artifacts if the root artifacts of all those artifacts have been through "Discard Sample" workflow

**Comment by tcezard** [comment]
updated the description
