### ISSUE TITLE
Spectramax Parsing

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/clarity_scripts#6]
The first step is to parse in the results from the Softmax software spectramax output file. This could not be done with the Clarity out of the box parser as it cannot handle the format of the text file.

[2016-08-10_X16084P001_1in10_QC.txt](https://github.com/EdinburghGenomics/clarity_scripts/files/451895/2016-08-10_X16084P001_1in10_QC.txt)

**Comment by tcezard** [comment]
duplicate of #13 
Closed

**Comment by mwhamgenomics** [comment]
Not actually a duplicate, as this describes processing of the Spectramax output file, while #13 describes automation of input templates.

**Comment by mwhamgenomics** [comment]
This was closed in #31.
